name: Cypress Full Suite Tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Dep installation
      run: npm install
    
    - name: Build the Docker image
      run: docker build -t cypress-image -f .Dockerfile .
    
    - name: Run bash script
      run: bash run_tests.sh

    - name: Upload Html report
      uses: actions/upload-artifact@v4
      with:
        name: Html-report
        path: cypress/reports/report.html

    - name: Test Report in GitHub Actions
      uses: phoenix-actions/test-reporting@v8
      if: always()
      with:
        name: Mochaawesome report
        path: cypress/reports/report.json
        reporter: mochawesome-json
