name: Cypress Full Suite Tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Dep installation
      run: npm install
    
    - name: Build the Docker image
      run: docker build -t cypress-image -f .Dockerfile .
    
    - name: Run bash script
      run: bash run_tests.sh
